```{r}
library(dplyr)
library(rvest)
library(rlang)
library(furrr)
library(doParallel)
library(foreach)
library(stringr)
```





```{r}
y <- readUrl("https://www.fpds.gov/ezsearch/fpdsportal?q=VENDOR_FULL_NAME%3A%22RAYTHEON+COMPANY%22+CONTRACT_FISCAL_YEAR%3A%221950%22&s=FPDS.GOV&templateName=1.5.2&indexName=awardfull&x=22&y=13")
if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))}
```


```{r}
y=read_html(paste('https://www.fpds.gov/ezsearch/fpdsportal?q=GLOBAL_VENDOR_NAME%3A"The+Boeing+Company"+CONTRACT_FISCAL_YEAR%3A%222010%22&s=FPDS.GOV&templateName=1.5.2&indexName=awardfull&x=22&y=13', sep="")) %>%  html_element(xpath='//b')
xml_attrs(y)
```

```{r}
  readUrl <- function(url) {
    out <- tryCatch(
        {
            x<- read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
            str_sub(x,-5,-1)
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
```


```{r}
Sys.setenv(http_proxy="http://proxyserver:port")
```

```{r}
parallel::detectCores()
n.cores <- parallel::detectCores() - 1
```
```{r}
#create the cluster
my.cluster <- parallel::makeCluster(
  n.cores, 
  type = "PSOCK"
  )

#check cluster definition (optional)
print(my.cluster)

#register it to be used by %dopar%
doParallel::registerDoParallel(cl = my.cluster)

#check if it is registered (optional)
foreach::getDoParRegistered()

#how many workers are available? (optional)
foreach::getDoParWorkers()
```



```{r}
contracts <- foreach(i = 1979:2022, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  y=read_html(paste("https://www.fpds.gov/ezsearch/fpdsportal?q=VENDOR_FULL_NAME%3A%22RAYTHEON+COMPANY%22+CONTRACT_FISCAL_YEAR%3A%22",as.character(i),"%22&s=FPDS.GOV&templateName=1.5.2&indexName=awardfull&x=22&y=13", sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```

```{r}
contracts1 <- foreach(i = 1965:1999, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?q=GLOBAL_VENDOR_NAME%3A"The+Boeing+Company"+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22&s=FPDS.GOV&templateName=1.5.2&indexName=awardfull&x=22&y=13',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```

```{r}
contracts2 <- foreach(i = 2000:2010, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?q=GLOBAL_VENDOR_NAME%3A"The+Boeing+Company"+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22&s=FPDS.GOV&templateName=1.5.2&indexName=awardfull&x=22&y=13',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```

```{r}
contracts3 <- foreach(i = 2011:2015, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?q=GLOBAL_VENDOR_NAME%3A"The+Boeing+Company"+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22&s=FPDS.GOV&templateName=1.5.2&indexName=awardfull&x=22&y=13',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```

```{r}
contracts4 <- foreach(i = 2016:2018, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?q=GLOBAL_VENDOR_NAME%3A"The+Boeing+Company"+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22&s=FPDS.GOV&templateName=1.5.2&indexName=awardfull&x=22&y=13',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```

```{r}
contracts5 <- foreach(i = 2019:2020, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?q=GLOBAL_VENDOR_NAME%3A"The+Boeing+Company"+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22&s=FPDS.GOV&templateName=1.5.2&indexName=awardfull&x=22&y=13',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```
```{r}
contracts6 <- foreach(i = 2021:2022, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?q=GLOBAL_VENDOR_NAME%3A"The+Boeing+Company"+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22&s=FPDS.GOV&templateName=1.5.2&indexName=awardfull&x=22&y=13',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```

```{r}
boeing<-rbind(contracts1, contracts2, contracts3, contracts4, contracts5, contracts6)
```

```{r}
contracts <- list()
for (j in 1:1) { 
df <- foreach(i = 1962+((j-1)*5):1966+((j-1)*5), .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?q=GLOBAL_VENDOR_NAME%3A"The+Boeing+Company"+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22&s=FPDS.GOV&templateName=1.5.2&indexName=awardfull&x=22&y=13',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
contracts[[i]] <-df
}
```

```{r}
contracts3 <- foreach(i = 2008:2012, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  y=read_html(paste('https://www.fpds.gov/ezsearch/fpdsportal?indexName=awardfull&templateName=1.5.2&s=FPDS.GOV&q=VENDOR_FULL_NAME%3A%22LOCKHEED+MARTIN+CORPORATION%22+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22&x=0&y=0', sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
   if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```

```{r}
grumman1 <- foreach(i = 1979:1989, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?indexName=awardfull&templateName=1.5.3&s=FPDS.GOV%2525252525252525252525252525252525252525252525252525252BtemplateName1.5.2%2525252525252525252525252525252525252525252525252525252BindexNameawardfull&q=GLOBAL_VENDOR_NAME%3A%22GRUMMAN+CORPORATION%22+CONTRACT_FISCAL_YEAR%3A%22',as,character(i),'%22+VENDOR_ADDRESS_STATE_CODE%3A%22MD%22&x=0&y=0',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```
```{r}
grumman2 <- foreach(i = 1990:2000, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?q=GLOBAL_VENDOR_NAME%3A"GRUMMAN+CORPORATION"+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22&s=FPDS.GOV&templateName=1.5.2&indexName=awardfull&x=0&y=0',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```


```{r}
lockheed1 <- foreach(i = 1976:1980, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?q=GLOBAL_VENDOR_NAME%3A"LOCKHEED+MARTIN+CORPORATION"+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22&s=FPDS.GOV&templateName=1.5.2&indexName=awardfull&x=0&y=0',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```

```{r}
lockheed2 <- foreach(i = 1981:1985, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?q=GLOBAL_VENDOR_NAME%3A"LOCKHEED+MARTIN+CORPORATION"+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22&s=FPDS.GOV&templateName=1.5.2&indexName=awardfull&x=0&y=0',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```



```{r}
parallel::stopCluster(cl = my.cluster)
```

```{r}
write.csv(contracts, "raytheonContracts.csv")
```

```{r}
write.csv(boeing, "boeingContracts.csv")
```

```{r}
for (i in 2010) { 
  y=read_html(paste("https://www.fpds.gov/ezsearch/fpdsportal?q=VENDOR_FULL_NAME%3A%22RAYTHEON+COMPANY%22+CONTRACT_FISCAL_YEAR%3A%22",as.character(i),"%22&s=FPDS.GOV&templateName=1.5.2&indexName=awardfull&x=22&y=13", sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
  year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
```

```{r}
raytheonMD <- foreach(i = 1994:2022, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?indexName=awardfull&templateName=1.5.3&s=FPDS.GOV%252525252525252525252525252525252BtemplateName1.5.2%252525252525252525252525252525252BindexNameawardfull&q=ULTIMATE_UEI_NAME%3A%22LOCKHEED%22+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22+VENDOR_ADDRESS_STATE_CODE%3A%22MD%22&x=24&y=13',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```

```{r}
grummanMD <- foreach(i = 1994:2022, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?indexName=awardfull&templateName=1.5.3&s=FPDS.GOV%2525252525252525252525252525252525252525252525252525252BtemplateName1.5.2%2525252525252525252525252525252525252525252525252525252BindexNameawardfull&q=GLOBAL_VENDOR_NAME%3A%22NORTHROP+GRUMMAN%22+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22+VENDOR_ADDRESS_STATE_CODE%3A%22MD%22&x=0&y=0',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```
```{r}
raytheonMD <- foreach(i = 1994:2022, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?indexName=awardfull&templateName=1.5.3&s=FPDS.GOV%252525252525252525252525252525252BtemplateName1.5.2%252525252525252525252525252525252BindexNameawardfull&q=ULTIMATE_UEI_NAME%3A%22RAYTHEON%22+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22+VENDOR_ADDRESS_STATE_CODE%3A%22MD%22&x=24&y=13',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```
```{r}
boeingMD <- foreach(i = 1994:2022, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?indexName=awardfull&templateName=1.5.3&s=FPDS.GOV%252525252525252525252525252525252BtemplateName1.5.2%252525252525252525252525252525252BindexNameawardfull&q=ULTIMATE_UEI_NAME%3A%22THE+BOEING+COMPANY%22+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22+VENDOR_ADDRESS_STATE_CODE%3A%22MD%22&x=24&y=13',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```
```{r}
generaldynamicsMD <- foreach(i = 1994:2022, .combine = 'rbind') %dopar% {
  library(rvest)
  library(dplyr)
  readUrl <- function(url) {
    out <- tryCatch(
        {
            read_html(paste(url, sep="")) %>% html_element(xpath='//*[(@id = "csvLink")]') %>% html_attr("href")
        },
        error=function(cond) {
            return(NA)
        },
        warning=function(cond) {
            return(NA)
        },
        finally={
        }
    )    
    return(out)
}
  y=readUrl(paste('https://www.fpds.gov/ezsearch/fpdsportal?indexName=awardfull&templateName=1.5.3&s=FPDS.GOV%252525252525252525252525252525252BtemplateName1.5.2%252525252525252525252525252525252BindexNameawardfull&q=ULTIMATE_UEI_NAME%3A%22GENERAL+DYNAMICS%22+CONTRACT_FISCAL_YEAR%3A%22',as.character(i),'%22+VENDOR_ADDRESS_STATE_CODE%3A%22MD%22&x=24&y=13',sep=""))
  if (is.na(y)==FALSE) { year_x <- read.csv(paste("https://www.fpds.gov/ezsearch/fpdsportal",y, sep=""))
  year_name <- paste("year",i, sep = "")
  assign(year_name,year_x) }
}
```

```{r}
write.csv(boeingMD, "boeingMD.csv")
write.csv(generaldynamicsMD, "generaldynamicsMD.csv")
write.csv(grummanMD, "grummanMD.csv")
write.csv(lockheedMD, "lockheedMD.csv")
write.csv(raytheonMD, "raytheonMD.csv")
```

