---
title: "Untitled"
author: "Ben Christensen"
date: "2022-10-27"
output: html_document
---



```{r}
library(tidyverse)
library(tidycensus)
library(sf)
library(ggplot2)
```

```{r}
raytheon <- read.csv("raytheonMD.csv") %>%
  mutate(company = "Raytheon")
boeing <- read.csv("boeingMD.csv") %>%
  mutate(company = "Boeing")
general <- read.csv("generaldynamicsMD.csv") %>%
  mutate(company = "General Dynamics")
grumman <- read.csv("grummanMD.csv") %>%
  mutate(company = "Northrop Grumman")
lockheed <- read.csv("lockheedMD.csv") %>%
  mutate(company = "Lockheed Martin")
cont <- rbind(raytheon, boeing, general, grumman, lockheed)
```
```{r}
zip <- read.csv("zip2020.csv")
```

```{r}
md_zip <- read.csv("Zip_Code_Lookup_Table.csv")
```


```{r}
zip1 <- zip %>%
  filter(nchar(GEOID) == 3) %>%
  mutate(zip = paste0("00",GEOID))
zip2 <- zip %>%
  filter(nchar(GEOID) ==4) %>%
  mutate(zip = paste0("0",GEOID))
zip3 <- zip %>%
  filter(nchar(GEOID) ==5) %>%
  mutate(zip = as.character(GEOID))
zipfix <- rbind(zip1,zip2,zip3)
```
```{r}
cont1 <- cont %>%
  filter(nchar(Entity.ZIP.Code)==4) %>%
  mutate(zip = paste0("0",Entity.ZIP.Code))
```

```{r}
cont1 <- cont %>%
  filter(nchar(Entity.ZIP.Code)==4) %>%
  mutate(zip = paste0("0",Entity.ZIP.Code))
```
```{r}
cont2 <- cont %>%
  filter(nchar(Entity.ZIP.Code)>5) %>%
  mutate(zip = as.character(Entity.ZIP.Code)) %>%
  mutate(zip = substr(zip,1,5))
```
```{r}
cont3 <- cont %>%
  filter(nchar(Entity.ZIP.Code)==5) %>%
  mutate(zip = as.character(Entity.ZIP.Code))
  
```

```{r}
contzip <- rbind(cont1, cont2, cont3)
```

```{r}
contzip<-contzip %>% 
  add_count(zip) %>%
  mutate(actionObligation = str_replace_all(Action.Obligation....,"\\$", ""), actionObligation = as.numeric(str_replace_all(actionObligation,",", ""))) %>%
  group_by(zip,company) %>%
  mutate(sum = sum(actionObligation))

```
```{r}
unique <- contzip %>% distinct(zip, n, sum, company)
```

```{r}
unique2 <- left_join(unique, zipfix,by=c("zip" = "zip"))
```



```{r}
zip <- st_read("tl_2010_us_zcta510")
```
```{r}
md_zip_full <- merge(md_zip, zip, by.x="Zip.Code", by.y ="ZCTA5CE10")
```

```{r}
MD_Merge <- left_join(md_zip_full, unique,by=c("GEOID10" = "zip"))
Merge <- left_join(MD_Merge, zipfix, by= c("GEOID10" = "zip"))
```
```{r}
Merge <- Merge %>% mutate(company = replace_na(company, "None"))
```

```{r}
usa <- st_as_sf(maps::map("state", fill=TRUE, plot =FALSE))
md <- st_as_sf(maps::map("state", "maryland", fill=TRUE, plot =FALSE))
ca <- st_as_sf(maps::map("state", "california", fill=TRUE, plot =FALSE))
```

```{r}

#ggplot() + geom_sf(data=usa)+ geom_sf(aes(size= sum, color = company), data=usa_sub) + theme(axis.text = element_blank(),
        #axis.ticks = element_blank(),
        #panel.grid.major = element_line('transparent'),
        #panel.background = element_blank(),
        #strip.text.x  = element_text(color='black', size = 20, face = 'bold', hjust=.5),
        #plot.title = element_text(color='black', size = 20, face = 'bold', hjust=.5),
        #plot.subtitle = element_text(color='black', size = 12, face = 'bold', hjust=.5),
        #legend.key.width = unit(.4, 'in'),
        #legend.title = element_text(color='black', size = 12, face='bold', vjust=.5, hjust=.5), 
        #legend.position = "bottom",
        #legend.direction='horizontal',
        #legend.text = element_text(color='black', size = 12, face='bold'))+
    #guides(fill = guide_colourbar(title = 'Company', 
#                                  title.position='top', title.hjust =.5))
```

```{r}
ggplot() + geom_sf(aes( fill= company, geometry=geometry), data=Merge) + theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.major = element_line('transparent'),
        panel.background = element_blank(),
        strip.text.x  = element_text(color='black', size = 20, face = 'bold', hjust=.5),
        plot.title = element_text(color='black', size = 20, face = 'bold', hjust=.5),
        plot.subtitle = element_text(color='black', size = 12, face = 'bold', hjust=.5),
        legend.key.width = unit(.4, 'in'),
        legend.title = element_text(color='black', size = 12, face='bold', vjust=.5, hjust=.5), 
        legend.position = "bottom",
        legend.direction='horizontal',
        legend.text = element_text(color='black', size = 12, face='bold'))+
    guides(fill = guide_legend(title = 'Company', 
                                  title.position='top', title.hjust =.5))
```


```{r}
column_names <- c("Maryland", "All Companies", "Lockheed Martin", "Northrop Grumman", "Raytheon", "Boeing", "General Dynamics" )

`Median Income` <- c("$44,669","$47,944","$52,301","$48,413","$47,364","$42,439","$44,988")
`Average Age` <- c(39.24, 38.15,38.40,38.41381, 38.59,36.10,37.84)
`Average Population per ZIP code` <- c("13,655.78", "29,395.89",  "36,857.92", "26,639.96", "24,867.79","34,512.5","30,149.81")
`Percent White` <- c("48.7%","50.51%", "45.68%", "52.64%","47.02%","32.16%","54.94%")

rbind(`Median Income`, `Average Age`,`Average Population per ZIP code`,`Percent White`) %>% 
  kableExtra::kable(align="c", caption = "Demogrpahics of Zip Codes of Defense Contractor Offices", col.names = column_names) %>%
  kableExtra::kable_styling(latex_options = c("hold_position"))

```

```{r}
weighted.mean(Merge$age,Merge$total_pop1, na.rm=TRUE)
mean(Merge$total_pop1, na.rm=TRUE)
weighted.mean(Merge$med_income,Merge$total_pop1/1000, na.rm=TRUE)
```
```{r}
companyonly <- Merge %>% filter(company!="None")
companyonly <- companyonly %>% mutate(whiteavg = white/total_pop1)
companyonly <- companyonly %>% mutate(whiteavg = replace_na(whiteavg, 0))
weighted.mean(companyonly$age,companyonly$total_pop1, na.rm=TRUE)
mean(companyonly$total_pop1, na.rm=TRUE)
weighted.mean(companyonly$med_income,companyonly$total_pop1/1000, na.rm=TRUE)
weighted.mean(companyonly$whiteavg,  na.rm=TRUE)
```

```{r}
companyonly <- Merge %>% filter(company=="Lockheed Martin")
companyonly <- companyonly %>% mutate(whiteavg = white/total_pop1)
companyonly <- companyonly %>% mutate(whiteavg = replace_na(whiteavg, 0))
weighted.mean(companyonly$age,companyonly$total_pop1, na.rm=TRUE)
mean(companyonly$total_pop1, na.rm=TRUE)
weighted.mean(companyonly$med_income,companyonly$total_pop1/1000, na.rm=TRUE)
weighted.mean(companyonly$whiteavg, companyonly$total_pop1/1000, na.rm=TRUE)
```
```{r}
companyonly <- Merge %>% filter(company=="Northrop Grumman")
companyonly <- companyonly %>% mutate(whiteavg = white/total_pop1)
companyonly <- companyonly %>% mutate(whiteavg = replace_na(whiteavg, 0))
weighted.mean(companyonly$age,companyonly$total_pop1, na.rm=TRUE)
mean(companyonly$total_pop1, na.rm=TRUE)
weighted.mean(companyonly$med_income,companyonly$total_pop1/1000, na.rm=TRUE)
weighted.mean(companyonly$whiteavg, companyonly$total_pop1/1000, na.rm=TRUE)
```
```{r}
companyonly <- Merge %>% filter(company=="Raytheon")
companyonly <- companyonly %>% mutate(whiteavg = white/total_pop1)
companyonly <- companyonly %>% mutate(whiteavg = replace_na(whiteavg, 0))
weighted.mean(companyonly$age,companyonly$total_pop1, na.rm=TRUE)
mean(companyonly$total_pop1, na.rm=TRUE)
weighted.mean(companyonly$med_income,companyonly$total_pop1/1000, na.rm=TRUE)
weighted.mean(companyonly$whiteavg, companyonly$total_pop1/1000, na.rm=TRUE)
```

```{r}
companyonly <- Merge %>% filter(company=="Boeing")
companyonly <- companyonly %>% mutate(whiteavg = white/total_pop1)
companyonly <- companyonly %>% mutate(whiteavg = replace_na(whiteavg, 0))
weighted.mean(companyonly$age,companyonly$total_pop1, na.rm=TRUE)
mean(companyonly$total_pop1, na.rm=TRUE)
weighted.mean(companyonly$med_income,companyonly$total_pop1/1000, na.rm=TRUE)
weighted.mean(companyonly$whiteavg, companyonly$total_pop1/1000, na.rm=TRUE)
```
```{r}
companyonly <- Merge %>% filter(company=="General Dynamics")
companyonly <- companyonly %>% mutate(whiteavg = white/total_pop1)
companyonly <- companyonly %>% mutate(whiteavg = replace_na(whiteavg, 0))
weighted.mean(companyonly$age,companyonly$total_pop1, na.rm=TRUE)
mean(companyonly$total_pop1, na.rm=TRUE)
weighted.mean(companyonly$med_income,companyonly$total_pop1/1000, na.rm=TRUE)
weighted.mean(companyonly$whiteavg, companyonly$total_pop1/1000, na.rm=TRUE)
```